name: Autograding Tests

on:

  - push
  - repository_dispatch


permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libc6-dev

    - name: Test 1 - Compilation Check
      id: test-compilation
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1 - Compilation Check
        setup-command: ''
        command: make clean && make all
        input: ''
        expected-output: '✓ all day 1 programs compiled successfully!'
        comparison-method: substring
        timeout: 10
        max-score: 33

    - name: Test 2 - Voltage Validation
      id: test-voltage
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2 - Voltage Validation
        setup-command: 'make clean && make all'
        command: ./tests/test_voltage
        input: ''
        expected-output: '✓ all tests passed!'
        comparison-method: included
        timeout: 10
        max-score: 33

    - name: Test 3 - Power Calculation
      id: test-power
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3 - Power Calculation
        setup-command: 'sudo apt-get update && sudo apt-get install -y gcc make libc6-dev && make clean && make all'
        command: ./tests/test_power
        input: ''
        expected-output: '✓ all tests passed!'
        comparison-method: included
        timeout: 10
        max-score: 34

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-COMPILATION_RESULTS: "${{steps.test-compilation.outputs.result}}"
        TEST-VOLTAGE_RESULTS: "${{steps.test-voltage.outputs.result}}"
        TEST-POWER_RESULTS: "${{steps.test-power.outputs.result}}"
      with:
        runners: test-compilation,test-voltage,test-power

